; Auto-generated snowflake movement data
; Generated by gen-snowflake-sine.py

snowflake_init_y
  !byte $00, $08, $10, $18, $20, $28, $30, $38
  !byte $40, $48, $50, $58, $60, $68, $70, $78
  !byte $80, $88, $90, $98, $a0, $a8, $b0, $b8
  !byte $c0, $c8, $d0, $d8, $e0, $e8, $f0, $f8
